### PR TITLE
[MRG] URL changes and redirects

### PR DESCRIPTION
**Pull request by michelfernandez**
We need to rename some URL's and therefore set up redirects. Concerning mainly jobs and on FR Maximize force probante page.

### CODE REVIEW

**Comment by michelfernandez** [comment]
Maxim checked the job page and gave the following feedback on Slack: 
Ist ok so. Kannst du mergen!

**Comment by Kirastina** [comment]
Looks good - redirects work.

**Comment by betatim** [comment]
Ready to go or needs more work (because of the WIP)?

**Comment by Kirastina** [comment]
One questio is still open - I'll mrg when cleared.

**Comment by michelfernandez** [comment]
Yeah, I saw it.
Left them as they were.
I'd like to watch it with Maxim. I've already texted him. 
Can you remember it like that?

**Pull request merged**
