### PR TITLE
[MRG] Create media and offering pages

### PR DESCRIPTION
**Pull request by michelfernandez**
- Content included for offering and media - languages: DE & EN
- Images included for offering and media

**Need some fine-tuning in frontend**

**Offering:**
- Button-Link: Get offer now
- Button-Link: More Information about identification

**Media:**
- exact media releases
- exact downloads of media releases
- exact download of brand-assets

**Footer:**
On the english version you don't see the link for the german version

Thanks!

### CODE REVIEW

**Comment by betatim** [comment]
Do we have a high resolution version of Kira's headshot for the media page https://deploy-preview-89--skribble.netlify.com/media? Right now on FF 67 you get a pixelated image :(

**Comment by fursinger** [comment]
@betatim, the styling for this PR is still completely missing. The image will be scaled down, so the pixelating effect should vanish.

**Comment by fursinger** [comment]
Ich übernehme diesen PR @michelfernandez. Bitte nicht mehr auf diesem Branch `new-content` arbeiten.

**Comment by fursinger** [comment]
**Offering** for Angebot sounds strange to my untrained ears. Is that a word you would use @betatim? Examples from other companies are 

- **Why Slack?** [slack]  
- **Features** [kipwise, dropbox, wordpress, jira]
- **Product** [asana]

**Comment by fursinger** [comment]
This PR als changes the identification page due to refactoring of shortcode architecture. It is necessary to thoroughly test all three pages (identification, media, offering) in all available languages.

**Comment by fursinger** [comment]
@michelfernandez, can you check the pages `identification`, `offering`, and `press room`? I rebuilt the entire layout system, so please scan through all pages and report anything that seems unusual. Thank you. 

@dkumpf1, can you also screen the entire page and report any abnormality? Thank you.

https://deploy-preview-89--skribble.netlify.com/

Heads up: Some of the pages are available in 3 languages (german, english, and french).

**Comment by fursinger** [comment]
@michelfernandez & @dkumpf1, thanks for your review. All suggestions have been included except for 2 issues:

- whitespace optimization on team page
- handling of text-alignment in `center-block` component

I suggest to look at these issues in a separate PR.

**Comment by betatim** [comment]
Can we merge this?

**Comment by fursinger** [comment]
According to @betatim, the page is better described as **product**, **services**, or **additional services**. 

> “offering” makes me think of offering a sacrifice to the gods.
@betatim

**Comment by fursinger** [comment]
Mike is pro **offering**.

**Comment by betatim** [comment]
Let's stick with this then. Maybe in the future we can figure out a different name/split the content or some such.

**Comment by fursinger** [comment]
@betatim, Luc also joined the discussion and the final outcome is: services. Everybody can agree on services 👍

**Comment by fursinger** [comment]
Tested by @michelfernandez, @dkumpf1, Simon, Kira and me. As discussed, I merge (and deploy) this PR.

**Pull request merged**
