### PR TITLE
[MRG] feat(Partners): Add new partners page in german

### PR DESCRIPTION
**Pull request by fursinger**
Introduces new partners and partner module.

### CODE REVIEW

**Comment by fursinger** [comment]
@TillLord can you take care of the SEO meta tags? I added a screenshot with TODO: that have to be completed before the PR can go online.

Screen Shot 2020-03-10 at 15 17 34

In case you need any help, let me know.

**Comment by TillLord** [comment]
@fursinger I added the meta titles, descriptions and alt texts but I don't know how to upload a pic to cove.

**Comment by fursinger** [comment]
Thanks @TillLord . Do you an image? You can send it to me an I'll add it. 

Name of the image should be `og-skribble-partners.jpg`.

**Comment by TillLord** [comment]
@fursinger thx! please finde attached the og_image
og-skribble-partners

**Comment by fursinger** [comment]
Nice. I'm fixing the reported issue by @dkumpf1 that all outros are in german. After that, we're ready to go online.

**Comment by dkumpf1** [comment]
[DEPLOY-PREVIEW]

Tested: OK

The above mentioned bug got fixed and it looks good in all languages. I also tested it again in all browsers and on my mobile device.

**Comment by ronioeschger** [comment]
The incomplete tests from netlify above are actually finished. So merging this now.

**Pull request merged**
