### PR TITLE
Skribble career for jobs

### PR DESCRIPTION
**Pull request by michelfernandez**
Created a career site for EN, DE, FR

### CODE REVIEW

**Comment by fursinger** [comment]
@TillLord @michelfernandez what's usus for posting jobs online? When a position is taken how do we handle the page? Is there gonna be a redirect to career? Or would it be better not to have specific pages for each job but let's say overlays or PDFs?

**Comment by TillLord** [comment]
It's more handy not to have specific pages for each job. We'll rank anyway just with our main /job (or /carrer) page.

**Comment by fursinger** [comment]
I quickly checked how GitHub, Slack, and Asana are dealing with jobs. They all create pages per job but add an id in the url. Out-of-date postings are all redirected to the parent page (`/jobs` or `/careers`). Might be a good way to do it. GitHub even removes the title from the url.

GitHub
https://boards.greenhouse.io/github/jobs/1896420

Slack
https://slack.com/intl/en-ch/careers/1968019/staff-data-scientist

Asana
https://asana.com/jobs/apply/721271/software-engineerinfrastructure

**Comment by betatim** [comment]
While we are nitpicking: why is it `karriere/job-sales-manager-de/` instead of `karriere/sales-manager-de/`? The "job" in the URL seems redundant.

I would vote for what the other companies do: once a job has been filled/no more job ad then we redirect it to `karriere/` with a permanent redirect. I don't think we should reuse a slug. So once `karriere/job-sales-manager-de/` has been used it can't be reused. If we get to the point where we want to reuse a slug like `sales-manager-de` I'd add a three digit number to it, so something like `sales-manager-de-481`. Chosen by rolling a dice :)

**Comment by fursinger** [comment]
Agree with @betatim on the `job` word. I'd also redirect stale offers to `/careers`.

It might be advantageous to have the id as a folder for SEO purposes instead of suffixing it to the encoded page title in the url. That is sth. that maybe @TillLord could answer.

**Pull request merged**
