### PR TITLE
[WIP] feat(404 on Netlify): Adds redirect for 404 errors

### PR DESCRIPTION
**Pull request by joaobarcia**
Should solve https://app.asana.com/0/995964219886332/1159420321924409/f

Wait for merge of new Cove structure first #283 .

Will be tricky to test/debug since the behavior only shows up on production skribble.com

### CODE REVIEW

**Comment by betatim** [comment]
Do we need a redirect? I thought we can specify a page to show on 404 in our netlify configuration.

**Comment by betatim** [comment]
Turns out after 60s of googling I found https://docs.netlify.com/routing/redirects/redirect-options/#http-status-codes which suggests using redirects :-)

**Comment by joaobarcia** [comment]
> Do we need a redirect? I thought we can specify a page to show on 404 in our netlify configuration.

That's actually a good question since it would make implementation a lot simpler :) The thing is, our 404.html is dynamically generated from an Hugo template. And it would have to be manually built and copy pasted to a place where Netlify recognizes it. So, it's really quick to do, but we'd be paying the technical debt in the future when someone goes like "I'm, changing the Hugo template, why doesn't it show up on the website?". If we manage to do it by redirects it will maintain our current best practice flow.

**Comment by joaobarcia** [comment]
Seems that https://github.com/BlockSigner/cove/pull/283 solved this issue. Closing the PR for now

**Pull request closed without merging**
