### PR TITLE
[MRG] (style): Single h1 per page

### PR DESCRIPTION
**Pull request by joaobarcia**
Solves https://app.asana.com/0/995964219886332/1162426209084529/f

### CODE REVIEW

**Comment by fursinger** [comment]
There is sth. off with the ordered lists on _**GTC**_ and _**Terms of Use**_ pages. Numbering starts with a 0 and resets after each header. In production, it looks alright, but cannot say if it's an effect of the changes in this PR. You wanna have a look at it?

**Comment by fursinger** [comment]
Another thing that I am thinking about is if we should make sure to have successive headers. For example, the page _**GTC**_ has a `h1` followed by a `h3` and then, a `h4`. I suspect that if we take care to have only one `h1` per page, we should probably also ensure to have a consistent hierarchical structure. So 'h1', 'h2', 'h3' for the _**GTC**_ page.

That's maybe something that @TillLord can say something about. Me, personally, I expect search engines to apply some sort of common sense to these things. But the approach with a single `h1` per page was that it cannot hurt. Any thoughts @TillLord ?

**Comment by TillLord** [comment]
From a SEO point of view it's not necessary to have a certain amount of h2-h6 titles or always the same structure of the page. But it would make sense from a UX perspective, since a clear structure of the content helps to read and to understand it better, which leads to a lower bounce-rate and a longer average visiting time, which leads in the end to a better seo ranking.

**Comment by fursinger** [comment]
I'm not talking about a certain amount of headers though. Talking about the order. What about the order, @TillLord ?

**Comment by TillLord** [comment]
According to John Mueller from Google the order of the h-tags on your web pages does not matter.
https://blog.seoprofiler.com/googles-john-mueller-the-order-of-your-headline-tags-does-not-matter/

**Comment by fursinger** [comment]
He also says that having multiple `h1` is as fine as having a random order🙈

I think that having changed the h1 but not changing the order is somewhat inconsistent. On the other hand, since it doesn't make a difference, we can leave it as it is and don't generate more work.

**Comment by TillLord** [comment]
h2-h6: The order and the number doesn't matter at all -> we don't have to produce extra work by changing or streamlining the pages.
h1: please set it at the beginning of each page and let's have just one h1. I want to rank with certain pages for certain keywords, when we have multiple h1 per page is's much harder to do so.

**Pull request merged**
