### PR TITLE
feat(Language switcher): Create new component in the heade…

### PR DESCRIPTION
**Pull request by fursinger**
Removes the language switcher from the footer. Removes all flags and add 3 custom round flags that are now also used in the navigation for mobile.

Closes https://app.asana.com/0/1151034440506477/1149735261955065

### CODE REVIEW

**Comment by fursinger** [comment]
**Before**

Screen Shot 2019-12-03 at 16 19 03

---------------------------------------------------------------------------------------------------

**Now**

Screen Shot 2019-12-03 at 16 17 54
---------------------------------------------------------------------------------------------------
Screen Shot 2019-12-03 at 16 18 14
---------------------------------------------------------------------------------------------------
Screen Shot 2019-12-03 at 16 18 46

**Comment by dkumpf1** [comment]
[DEPLOY-PREVIEW]

Tested: NOT OK

The french flagg is not fully visible in FF/Edge and Chrome/Native Browser on mobile Samsung Galaxy S7 Edge. You can see everything in the asana ticket:
https://app.asana.com/0/1151034440506477/1149735261955065

**Comment by fursinger** [comment]
A little tricky to test for me, but could you have another look @dkumpf1? You should be able to immediately see if it's fixed now.

**Comment by dkumpf1** [comment]
[DEPLOY-PREVIEW]

**Tested: OK**

Now the flags look alike and they aren't cut off.

**Comment by fursinger** [comment]
Ready to merge.

**Pull request merged**
