### PR TITLE
[MRG] feat(IE): Add fallback page to redirect to from wave

### PR DESCRIPTION
**Pull request by fursinger**
To start with, we create an english page. IE users from WAVE will be redirected to this page that asks them to please use another browser.

### CODE REVIEW

**Comment by fursinger** [comment]
@dkumpf1 please have a look at this page with IE11. The text should be readable and the Links to the browsers should work. It's english only.

**Comment by dkumpf1** [comment]
[DEPLOY-PREVIEW]

Tested: OK

I found 2 smaller bugs, which will be fixed by David. I will re-test this then, but it looks overall fine enough.

**Comment by dkumpf1** [comment]
[DEPLOY-PREVIEW]

**Tested: OK**

The bugs got fixed and it looks good now. The redirection of the links is now correct.

**Comment by fursinger** [comment]
@TillLord shall we disallow the `/ie-fallback` in the robots.txt?

**Comment by TillLord** [comment]
@fursinger yes, good idea. I don't see why we would want to rank with the ie-fallback page in any case.

**Pull request merged**
