### PR TITLE
[MRG] feat(Pricing page): New page for prices explanation

### PR DESCRIPTION
**Pull request by joaobarcia**

### CODE REVIEW

**Comment by betatim** [comment]
We should only merge this into `magic-monday` if we have the payment stuff in wave ready to go. Otherwise let's hold off on merging this.

**Comment by fursinger** [comment]
@joaobarcia can we merge `master` into this feature branch and resolve the conflicts? I guess @michelfernandez added lots of little content optimisations last week. Maybe you and @michelfernandez can resolve the conflicts together.

**Comment by fursinger** [comment]
I merged with the help of @betatim.

**Comment by michelfernandez** [comment]
Only missing: 
- Compare features for EN, FR

**Comment by betatim** [comment]
We need to sync the content here and in the plans page of the platform. In particular the tiles describing each plan are different so we should make sure we have the same text in both.

**Comment by fursinger** [comment]
@betatim good input. The tough question: what text from which source? :D 
I guess that both versions have already had corrections implemented.

Screen Shot 2019-10-24 at 15 34 37

**Comment by betatim** [comment]
I went with updates from platform -> cove. In particular for French it would be good to have someone who speaks French take a look.

**Pull request merged**
