### PR TITLE
[MRG] feat(Verticals): Adding lawyer vertical and hr horizontal

### PR DESCRIPTION
**Pull request by fursinger**
Adds the new horizontal marketing page to Cove.

### CODE REVIEW

**Comment by fursinger** [comment]
@dkumpf1 please test the new pages.

New pages are **HR** and **Laywer**. Use the footer menu to navigate there. 

**HR**
Screen Shot 2019-08-29 at 11 14 33

**Lawyer**
Screen Shot 2019-08-29 at 11 14 44

**Comment by fursinger** [comment]
@dkumpf1, ist das getestet und von dir aus ready to merge?

**Comment by fursinger** [comment]
@michelfernandez von dir aus ist das ready zum live stellen, korrekt?

**Comment by dkumpf1** [comment]
I tested https://app.asana.com/0/1138046704227938/1137679673120810 and with this the PR can go live.

**Comment by michelfernandez** [comment]
Let's merge! Till will later adjust the metatags and alt-tags.

**Pull request merged**
