### PR TITLE
[MRG] Add GTC in Footer

### PR DESCRIPTION
**Pull request by michelfernandez**
- Changed position of copyright
- Add GTC-Link in footer for EN, DE, FR

### CODE REVIEW

**Comment by fursinger** [comment]
@michelfernandez, the `© 2019 Skribble` is at the start of the list now. Is that intended?

**Comment by michelfernandez** [comment]
> @michelfernandez, the `© 2019 Skribble` is at the start of the list now. Is that intended?

Yes. Thanks!

**Comment by fursinger** [comment]
> > @michelfernandez, the `© 2019 Skribble` is at the start of the list now. Is that intended?
> 
> Yes. Thanks!

Okay

**Comment by fursinger** [comment]
Do we want to call it `General Terms and Conditions` in english, because it's quite long. I checked other websites. Most call it `terms` (GitHub, Asana, Slack) which in my opinion would be a bit better. What do you think @michelfernandez?

**Comment by michelfernandez** [comment]
> Do we want to call it `General Terms and Conditions` in english, because it's quite long. I checked other websites. Most call it `terms` (GitHub, Asana, Slack) which in my opinion would be a bit better. What do you think @michelfernandez?

That would be great, found it also long! Should I adjust it?

**Comment by fursinger** [comment]
Yeah, please change to `Terms`. If someone has a different opinion, we can still change it later.

**Pull request merged**
